"""esquema inicial

Revision ID: 0001
Revises: 
Create Date: 2026-09-29 09:51:58.698361
"""
from alembic import op
import sqlalchemy as sa


revision = '0001'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('listing',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(length=1024), nullable=False),
    sa.Column('titulo', sa.String(length=512), nullable=False),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('m2', sa.Integer(), nullable=True),
    sa.Column('habitaciones', sa.Integer(), nullable=True),
    sa.Column('banos', sa.Integer(), nullable=True),
    sa.Column('municipio', sa.String(length=128), nullable=False),
    sa.Column('fuente', sa.String(length=64), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('datos_insuficientes', sa.Boolean(), nullable=False),
    sa.Column('estado', sa.String(length=16), nullable=False),
    sa.Column('primera_aparicion', sa.Date(), nullable=False),
    sa.Column('ultima_aparicion', sa.Date(), nullable=False),
    sa.Column('precio_anterior', sa.Integer(), nullable=True),
    sa.Column('bajada_precio', sa.Integer(), nullable=True),
    sa.Column('precio_candidato', sa.Integer(), nullable=True),
    sa.Column('detalle', sa.JSON(), nullable=False),
    sa.Column('creado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listing_estado'), ['estado'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_municipio'), ['municipio'], unique=False)
        batch_op.create_index(batch_op.f('ix_listing_url'), ['url'], unique=True)

    op.create_table('pasada_diaria',
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('total_listings', sa.Integer(), nullable=False),
    sa.Column('score_medio', sa.Float(), nullable=True),
    sa.Column('precio_medio', sa.Integer(), nullable=True),
    sa.Column('precio_min', sa.Integer(), nullable=True),
    sa.Column('precio_max', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('fecha')
    )
    op.create_table('precio_referencia',
    sa.Column('municipio', sa.String(length=128), nullable=False),
    sa.Column('mediana_eur_m2', sa.Float(), nullable=False),
    sa.Column('actualizado_en', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('municipio')
    )
    op.create_table('historial_precio',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('precio_anterior', sa.Integer(), nullable=False),
    sa.Column('precio_nuevo', sa.Integer(), nullable=False),
    sa.Column('fecha_cambio', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['listing_id'], ['listing.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('historial_precio', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_historial_precio_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('historial_precio', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_historial_precio_listing_id'))

    op.drop_table('historial_precio')
    op.drop_table('precio_referencia')
    op.drop_table('pasada_diaria')
    with op.batch_alter_table('listing', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listing_url'))
        batch_op.drop_index(batch_op.f('ix_listing_municipio'))
        batch_op.drop_index(batch_op.f('ix_listing_estado'))

    op.drop_table('listing')
    # ### end Alembic commands ###
